import {describe,it,expect,vi} from 'vitest';
import {readFileSync,existsSync} from 'node:fs';
import {AUDIO_KEY,GameAudio,MUSIC,EFFECTS,readAudioPreferences} from '../src/coconut/audio';
class Param{value=0;setValueAtTime(v:number){this.value=v;}linearRampToValueAtTime(v:number){this.value=v;}cancelAndHoldAtTime(){}cancelScheduledValues(){}setValueCurveAtTime(v:Float32Array){this.value=v[v.length-1];}}
class Node{gain=new Param();buffer?:AudioBuffer;loop=false;loopStart=0;loopEnd=0;started=false;stopped=false;onended?:()=>void;connect(){}disconnect(){}start(){this.started=true;}stop(){this.stopped=true;this.onended?.();}}
class Context{state='suspended';currentTime=0;destination={};sources:Node[]=[];createGain(){return new Node();}createBufferSource(){const n=new Node();this.sources.push(n);return n;}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}close(){this.state='closed';return Promise.resolve();}decodeAudioData(){return Promise.resolve({duration:3} as AudioBuffer);}}
const tick=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function harness(saved?:object){
 const values=new Map<string,string>();if(saved)values.set(AUDIO_KEY,JSON.stringify(saved));
 const storage={getItem:(k:string)=>values.get(k)||null,setItem:(k:string,v:string)=>void values.set(k,v)};
 const context=new Context(),createContext=vi.fn(()=>context as unknown as AudioContext);
 const fetcher=vi.fn(async(_url:RequestInfo|URL,_init?:RequestInit)=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)} as Response));let time=0;
 const audio=new GameAudio({storage,createContext,fetcher,now:()=>time});
 return {audio,context,createContext,fetcher,storage,time:(value:number)=>time=value,enable:async()=>{audio.setPreferences({master:true});await tick();}};
}
describe('quiet audio preferences',()=>{
 it('defaults to explicit opt-in with separate gentle channel levels',()=>{const h=harness();expect(h.audio.preferences).toEqual({master:false,bgm:true,sfx:true,bgmVolume:.55,sfxVolume:.8});expect(h.createContext).not.toHaveBeenCalled();});
 it('never creates a context or fetches assets on a cold silent input',async()=>{const h=harness();expect(await h.audio.unlock()).toBe(false);expect(await h.audio.play('ui_tap')).toBe(false);expect(h.createContext).not.toHaveBeenCalled();expect(h.fetcher).not.toHaveBeenCalled();});
 it('sanitizes malformed and unavailable storage',()=>{for(const raw of ['bad','null','[]'])expect(readAudioPreferences({getItem:()=>raw,setItem(){}}).master).toBe(false);expect(readAudioPreferences({getItem(){throw Error();},setItem(){}}).master).toBe(false);const h=harness({master:true,bgm:'wrong',sfx:false,bgmVolume:3,sfxVolume:-1});expect(h.audio.preferences).toEqual({master:true,bgm:true,sfx:false,bgmVolume:1,sfxVolume:0});});
 it('persists master, channel switches and levels without auto-playing on reload',async()=>{const h=harness();h.audio.setPreferences({master:true,bgm:false,sfx:true,bgmVolume:.31,sfxVolume:.62});await tick();const fresh=new GameAudio({storage:h.storage,createContext:h.createContext});expect(fresh.preferences).toEqual(h.audio.preferences);expect(fresh.context).toBeUndefined();expect(h.createContext).toHaveBeenCalledTimes(1);});
});
describe('music lifecycle and races',()=>{
 it('starts only after opt-in and maintains exact loop points',async()=>{const h=harness();await h.enable();expect(h.audio.loops.size).toBe(1);expect(h.context.sources[0].loopEnd).toBe(MUSIC.menu.duration);h.audio.setScene('play');await tick();expect([...h.audio.loops].map(x=>x.scene)).toEqual(['play']);expect(h.context.sources.at(-1)?.loopEnd).toBe(MUSIC.play.duration);});
 it('keeps one loop through repeated starts and scene switches',async()=>{const h=harness();await h.enable();for(let i=0;i<5;i++){h.audio.setScene('play');h.audio.setScene('menu');h.audio.setScene('play');await tick();}expect([...h.audio.loops].map(x=>x.scene)).toEqual(['play']);expect(h.context.sources.filter(x=>x.loop&&x.started&&!x.stopped)).toHaveLength(1);});
 it('deduplicates pending asset requests',async()=>{const h=harness();await h.enable();h.audio.buffers.delete('ui_tap');h.fetcher.mockClear();await Promise.all([h.audio.load('ui_tap'),h.audio.load('ui_tap'),h.audio.load('ui_tap')]);expect(h.fetcher).toHaveBeenCalledTimes(1);});
 it('falls back to WAV after unsupported Ogg and tolerates total failure',async()=>{const h=harness();await h.enable();h.audio.buffers.clear();h.fetcher.mockImplementation(async(url)=>{if(String(url).endsWith('.ogg'))throw Error('unsupported');return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)} as Response;});expect(await h.audio.load('menu')).toBeTruthy();expect(h.fetcher.mock.calls.map(x=>x[0]).join(' ')).toContain('.wav');h.audio.buffers.clear();h.fetcher.mockImplementation(async()=>{throw Error('offline');});expect(await h.audio.load('play')).toBeNull();expect(await h.audio.play('invalid_soft')).toBe(false);});
 it('does not start a late music load after mute',async()=>{const h=harness();await h.enable();let resolve!:(value:Response)=>void;h.fetcher.mockImplementation(()=>new Promise(r=>resolve=r));h.audio.setScene('play');h.audio.setPreferences({master:false});resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)} as Response);await tick();expect(h.audio.loops.size).toBe(0);expect(h.context.state).toBe('suspended');});
 it('pauses in background, discards cues, and resumes only enabled audio',async()=>{const h=harness();await h.enable();await h.audio.play('match_gp');h.audio.setHidden(true);expect(h.context.state).toBe('suspended');expect(h.audio.voices.size).toBe(0);expect(await h.audio.play('clear')).toBe(false);h.audio.setHidden(false);await tick();expect(h.context.state).toBe('running');expect(h.audio.loops.size).toBe(1);h.audio.setHidden(true);h.audio.setPreferences({master:false});h.audio.setHidden(false);await tick();expect(h.context.state).toBe('suspended');});
 it('retains channel levels after mute and cannot resume an unapproved session',async()=>{const h=harness();h.audio.setHidden(true);h.audio.setHidden(false);await tick();expect(h.createContext).not.toHaveBeenCalled();await h.enable();h.audio.setPreferences({bgmVolume:.2,sfxVolume:.4});h.audio.setPreferences({master:false});h.audio.setPreferences({master:true});await tick();expect(h.audio.preferences.bgmVolume).toBe(.2);expect(h.audio.preferences.sfxVolume).toBe(.4);expect(h.audio.loops.size).toBe(1);});
});
describe('gameplay-only cues',()=>{
 it('supports only the six card cues and actual clear/completion jingles',()=>{expect(EFFECTS).toEqual(['ui_tap','deselect','match_ap','match_gp','invalid_soft','blocked_tile']);const src=readFileSync(new URL('../src/coconut/main.tsx',import.meta.url),'utf8');expect(src).not.toMatch(/audio\.play\('(undo|retry|fresh_start)'/);const undo=src.slice(src.indexOf(' function undo()'),src.indexOf(' const values=',src.indexOf(' function undo()')));expect(undo).toContain('audio.stopTransient()');expect(undo).not.toContain('audio.play');const start=src.slice(src.indexOf(' function start('),src.indexOf(' function tap('));expect(start).not.toContain('audio.play');});
 it('throttles repeated taps and caps non-result polyphony',async()=>{const h=harness();await h.enable();expect(await h.audio.play('ui_tap')).toBe(true);expect(await h.audio.play('ui_tap')).toBe(false);for(let i=0;i<6;i++){h.time(i*100+100);await h.audio.play('deselect');}expect(h.audio.voices.size).toBe(3);});
 it('ducks music for one jingle and cancels it on navigation/restart',async()=>{const h=harness();await h.enable();await h.audio.play('clear');expect(h.audio.voices.size).toBe(1);expect(h.audio.musicGain!.gain.value).toBeCloseTo(.11);expect(await h.audio.play('deselect')).toBe(false);await h.audio.play('complete');expect(h.audio.voices.size).toBe(1);h.audio.setScene('play');await tick();expect(h.audio.voices.size).toBe(0);expect(h.audio.musicGain!.gain.value).toBe(.55);});
 it('drops delayed effects and stale result loads after navigation',async()=>{const h=harness();await h.enable();h.audio.buffers.delete('deselect');let resolve!:(value:Response)=>void;h.fetcher.mockImplementation(()=>new Promise(r=>resolve=r));const cue=h.audio.play('deselect');h.time(300);resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)} as Response);expect(await cue).toBe(false);h.audio.buffers.delete('complete');const result=h.audio.play('complete');h.audio.setScene('menu');resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)} as Response);expect(await result).toBe(false);});
 it('does not play muted channels and disposes sources safely',async()=>{const h=harness();await h.enable();h.audio.setPreferences({sfx:false});expect(await h.audio.play('clear')).toBe(false);h.audio.setPreferences({bgm:false});await tick();expect(h.audio.loops.size).toBe(0);h.audio.dispose();expect(h.context.state).toBe('closed');expect(await h.audio.unlock()).toBe(false);});
 it('ships exact-duration WAV fallbacks and leaves unused button/retry cues unshipped',()=>{const manifest=JSON.parse(readFileSync(new URL('../docs/audio-source-manifest.json',import.meta.url),'utf8'));for(const a of manifest.assets){const file=new URL('../public/audio/'+a.wav,import.meta.url);if(a.id==='undo'||a.id==='04_fresh_start'){expect(existsSync(file)).toBe(false);continue;}const bytes=readFileSync(file);expect(bytes.length).toBe((a.id==='02_tidal_patterns_play'?2560000:a.frames)*4+44);if(a.id==='02_tidal_patterns_play')expect(bytes.readUInt32LE(24)).toBe(28000);expect(bytes.toString('ascii',0,4)).toBe('RIFF');}});
});
